apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-fastapi
spec:
  rules:
    - host: hello-fastapi.local
    - ingressClassName: nginx
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-fastapi
                port:
                  number: 80
