---
name: CI - Docker Build and GitOps Deploy

on:
  push:
    branches:
      - main
permissions:
  contents: write

env:
  REGISTRY: docker.io
  IMAGE_NAME: fastapi-distroless

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: hello-fastapi
          file: hello-fastapi/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Update Kubernetes manifest
        run: |
          sed -i \
            "s|image:.*|image: ${REGISTRY}/${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${IMAGE_TAG}|g" \
            k8s/deployment.yaml
            - name: Commit GitOps update
            env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            
            git add k8s/deployment.yaml
            # We check if there are changes to avoid empty commit errors
            git commit -m "gitops: deploy image ${IMAGE_TAG}" || echo "No changes to commit"
            
            # Force a pull rebase to sync with remote before pushing
            git pull origin main --rebase
            
            # Push using the built-in GITHUB_TOKEN permissions
            git push origin main





