name: GitOps with Terraform + Argo CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - k8s/**

permissions:
  contents: write

env:
  IMAGE_NAME: fastapi-distroless
  REGISTRY: docker.io

jobs:
  gitops-exam:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Create local Kubernetes cluster
      - name: Create kind cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: exam-cluster

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraform init & apply (Argo CD bootstrap)
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply (Install Argo CD)
        working-directory: terraform
        run: terraform apply -auto-approve

      # Set image tag
      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Setup Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & push image
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: hello-fastapi
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      #  Update GitOps manifest
      - name: Update deployment image
        run: |
          sed -i \
            "s|image:.*|image: ${REGISTRY}/${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${IMAGE_TAG}|g" \
            k8s/deployment.yaml

      #  Commit and push GitOps change
      - name: Commit GitOps update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "gitops: deploy ${IMAGE_TAG}" || exit 0
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/nalini1223/GitOps.git
          for i in {1..5}; do
            echo "Attempt $i to sync and push..."
            git pull --rebase origin main && \
            git push origin main && break || \
            (echo "Conflict detected, retrying in 5s..." && sleep 5)
          done

       # CI prints the exact image tag + pull command
      - name: Show deployed image and local pull command
        run: |
                echo "Deployed image:"
                kubectl get deployment hello-fastapi \
                  -n hello-fastapi \
                  -o jsonpath='{.spec.template.spec.containers[0].image}'
                echo ""
                echo ""
                echo "To pull locally, run:"
                echo "docker pull docker.io/naliniudayt/fastapi-distroless:${IMAGE_TAG}"


    




