name: CI - Docker Build and GitOps Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'

permissions:
  contents: write

env:
  REGISTRY: docker.io
  IMAGE_NAME: fastapi-distroless

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: hello-fastapi
          file: hello-fastapi/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Update Kubernetes manifest
        run: |
          sed -i \
            "s|image:.*|image: ${REGISTRY}/${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${IMAGE_TAG}|g" \
            k8s/deployment.yaml
      - name: Commit GitOps update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 1. Setup Identity
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # 2. FORCE the runner to be on the real main branch
          git checkout -B main
          
          # 3. Pull the latest changes from remote
          git pull https://x-access-token:${GITHUB_TOKEN}@github.com/nalini1223/GitOps.git main

          # 4. Re-apply the manifest change (just in case the pull overwrote it)
          sed -i "s|image:.*|image: ${REGISTRY}/${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${IMAGE_TAG}|g" k8s/deployment.yaml

          # 5. Commit and Push
          git add k8s/deployment.yaml
          git commit -m "gitops: deploy image ${{ env.IMAGE_TAG }}" || echo "No changes to commit"
          
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/nalini1223/GitOps.git main

    




