---
name: CI - Docker Build and GitOps Deploy

on:
  push:
    branches:
      - main
permissions:
  contents: write

env:
  REGISTRY: docker.io
  IMAGE_NAME: fastapi-distroless

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history so rebase works smoothly

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: hello-fastapi
          file: hello-fastapi/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Update Kubernetes manifest
        run: |
          sed -i \
            "s|image:.*|image: ${REGISTRY}/${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${IMAGE_TAG}|g" \
            k8s/deployment.yaml
            
            - name: Commit GitOps update
            env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              # 1. Identity
              git config user.name "github-actions"
              git config user.email "github-actions@github.com"
              
              # 2. Stage and Commit
              git add k8s/deployment.yaml
              git commit -m "gitops: deploy image ${IMAGE_TAG}" || echo "No changes to commit"
              
              # 3. SYNC (This fixes the 'rejected' error)
              # This pulls latest changes and puts your commit on top of them
              git pull origin main --rebase
              
              # 4. Push using the authenticated URL
              git push https://x-access-token:${GITHUB_TOKEN}@github.com/nalini1223/GitOps.git HEAD:main





